/**
 * Seed the common gym-exercise catalog (backend/data/gym-exercises.json) and
 * enhance existing common exercises with the new force/mechanic fields.
 *
 * - Dedupe is case-insensitive by name; existing docs are never overwritten.
 * - Prints INSERTED_IDS=[...] at the end — save it, it's the rollback artifact
 *   (db.exercises.deleteMany({_id: {$in: [...]}})).
 * - Embeddings are generated by the Exercise pre-save hook during create
 *   (requires OPENAI_API_KEY; fail-soft). Run scripts/backfillEmbeddings.js
 *   afterwards to batch-embed anything the hook missed and to re-embed the
 *   enhanced existing docs.
 *
 * Usage:  node scripts/seedGymExercises.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Exercise = require('../src/models/Exercise');
const User = require('../src/models/User');
const gymExercises = require('../data/gym-exercises.json');

// force/mechanic enrichment for the pre-existing common catalog (calisthenics).
// Only names with an unambiguous classification are listed; updateOne bypasses
// the pre-save hook, so the backfill script re-embeds these with the new text.
const EXISTING_ENHANCEMENTS = {
  'Band Straight Arm Lat Pull Down': { force: 'pull', mechanic: 'isolation' },
  'Explosive Pull Ups': { force: 'pull', mechanic: 'compound' },
  'Explosive Straight Bar Dips': { force: 'push', mechanic: 'compound' },
  'Hanging L-Sit Hold': { force: 'static', mechanic: 'compound' },
  'Deep Pike Push Ups': { force: 'push', mechanic: 'compound' },
  'Bodyweight Rows Supinate Grip': { force: 'pull', mechanic: 'compound' },
  'Reverse Hyperextension': { force: 'pull', mechanic: 'isolation' },
  'Toes To Bar': { force: 'pull', mechanic: 'compound' },
  'Prone Y Raises': { force: 'pull', mechanic: 'isolation' },
  'German Hang': { force: 'static' },
  'Pull-Ups + Top Hold': { force: 'pull', mechanic: 'compound' },
  'Regular Dips': { force: 'push', mechanic: 'compound' },
  'Alternating Pistol Squats': { force: 'push', mechanic: 'compound' },
  'Hollow Body Hold': { force: 'static', mechanic: 'isolation' },
  'Glute Bridges': { force: 'push', mechanic: 'compound' },
  'Russian Twists': { force: 'pull', mechanic: 'compound' },
  'Low Squat Hold': { force: 'static', mechanic: 'compound' },
  'Skin the Cat': { force: 'pull', mechanic: 'compound' },
  'German Hang Pull Outs + Hold': { force: 'pull', mechanic: 'compound' },
  'Bodyweight Rows (Low Intensity)': { force: 'pull', mechanic: 'compound' },
  'Reverse Flies on Rings': { force: 'pull', mechanic: 'isolation' },
  'Alternating Archer Push Ups': { force: 'push', mechanic: 'compound' },
  'Wall Walks': { force: 'push', mechanic: 'compound' },
  'BW Hamstring Curls': { force: 'pull', mechanic: 'isolation' },
  'Seated Pike Compressions + Hold': { force: 'pull', mechanic: 'isolation' },
  'Active Hang': { force: 'static' },
  'Floor Elbow Victorian Hold': { force: 'static', mechanic: 'compound' },
  'L-Sit Hold on Parallettes': { force: 'static', mechanic: 'compound' },
  'Pull Over to Negative Muscle Up': { force: 'pull', mechanic: 'compound' },
  'Frenchie Chin-Ups': { force: 'pull', mechanic: 'compound' },
  'Diamond to Regular Push-Ups': { force: 'push', mechanic: 'compound' },
  'Prisoner/Bodyweight Jumping Squat': { force: 'push', mechanic: 'compound' },
  'Explosive Bodyweight Rows': { force: 'pull', mechanic: 'compound' },
  'Pike Push-Ups': { force: 'push', mechanic: 'compound' },
  'Side Plank On Arms': { force: 'static', mechanic: 'isolation' },
  'Face Pulls': { force: 'pull', mechanic: 'compound' },
  'Cuban Rotations': { force: 'pull', mechanic: 'isolation' },
  'Slow Push Up': { force: 'push', mechanic: 'compound' },
  'Seated Forward Fold': { force: 'static' },
  'Pancake Stretch': { force: 'static' },
  'Low Squat': { force: 'static' },
  'Hero Pose': { force: 'static' },
  'Laying Butterfly': { force: 'static' },
  'Lower Body Stretch': { force: 'static' },
  'Assisted Shoulder Stretch': { force: 'static' },
  'Butterfly Forward Fold': { force: 'static' },
  'Frog Pose': { force: 'static' },
  'Wall Assisted Shoulder Flexion Stretch': { force: 'static' },
  'Bar Assisted Shoulder Flexion Stretch': { force: 'static' }
};

const escapeRegex = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

async function seedGymExercises() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/ripped-potato');
    console.log('Connected to MongoDB');

    let adminUser = await User.findOne({ role: 'admin' });
    if (!adminUser) {
      console.log('Admin user not found, creating one...');
      adminUser = await User.create({
        email: 'admin@synergyfit.com',
        name: 'Admin User',
        role: 'admin',
        password: 'temp-admin-password-change-this'
      });
    }

    // --- 1. Insert new gym exercises ---------------------------------------
    console.log(`Seeding ${gymExercises.length} gym exercises...`);
    const insertedIds = [];
    let skipped = 0;
    let failed = 0;

    for (const exerciseData of gymExercises) {
      const existing = await Exercise.findOne({
        name: new RegExp(`^${escapeRegex(exerciseData.name)}$`, 'i')
      });
      if (existing) {
        console.log(`Exists, skipping: ${exerciseData.name}`);
        skipped += 1;
        continue;
      }

      try {
        const created = await Exercise.create({
          ...exerciseData,
          createdBy: adminUser._id
        });
        insertedIds.push(created._id.toString());
        console.log(`Created: ${exerciseData.name}`);
      } catch (err) {
        failed += 1;
        console.error(`FAILED: ${exerciseData.name} — ${err.message}`);
      }
    }

    // --- 2. Enhance existing commons with force/mechanic --------------------
    let enhanced = 0;
    for (const [name, fields] of Object.entries(EXISTING_ENHANCEMENTS)) {
      const res = await Exercise.updateOne(
        { name, isCommon: true, mechanic: { $exists: false }, force: { $exists: false } },
        { $set: fields }
      );
      if (res.modifiedCount) {
        enhanced += 1;
      }
    }
    console.log(`Enhanced ${enhanced} existing common exercises with force/mechanic`);

    // --- 3. Normalize legacy equipment tokens -------------------------------
    const norm = await Exercise.updateMany(
      { equipment: { $in: ['dumbbells', 'Dumbbells'] } },
      { $set: { 'equipment.$[el]': 'dumbbell' } },
      { arrayFilters: [{ el: { $in: ['dumbbells', 'Dumbbells'] } }] }
    );
    console.log(`Normalized equipment tokens on ${norm.modifiedCount} docs`);

    // --- 4. Summary ----------------------------------------------------------
    const missingEmbedding = insertedIds.length
      ? await Exercise.countDocuments({
          _id: { $in: insertedIds },
          embedding: { $exists: false }
        })
      : 0;

    console.log('--- Summary ---');
    console.log(`Created: ${insertedIds.length}, skipped: ${skipped}, failed: ${failed}, enhanced: ${enhanced}`);
    console.log(`New docs missing embedding (run backfillEmbeddings.js): ${missingEmbedding}`);
    console.log('INSERTED_IDS=' + JSON.stringify(insertedIds));

    await mongoose.disconnect();
    process.exit(failed > 0 ? 1 : 0);
  } catch (error) {
    console.error('Error seeding gym exercises:', error);
    process.exit(1);
  }
}

seedGymExercises();
